packages:
  - packages/*
  - examples

ignoredBuiltDependencies:
  - node-pty
  - protobufjs

onlyBuiltDependencies:
  - aws-sdk
  - bufferutil
  - esbuild

overrides:
  list: link:C:/Users/kaddouri/AppData/Local/pnpm/global/5/node_modules/list
